#!/usr/bin/env bash

function run {
  ./node_modules/.bin/babel-node ./lib/index.js \
    --vehicles  $1 \
    --locations $2 \
    --csv $3
}

function help {
  echo "
  Usage for ./scrape...

    EXAMPLE

      ./scrape -v vehicles.csv -l locations.csv -o out.csv

    OPTIONS

      -v : csv file of vehicles to scrape, must contain 'Make' and 'Model' columns
            additionally, vehicle make and model must appear on lookup on edmunds.com

      -l : csv file of locations to scrape, must contain 'ZIP'

      -o : (optional) filename of output csv, if omitted, data will be output
           to file named 'results_(unix timestamp).csv'

      -h : show this message
  "
}

VEHICLE_FILE=" "
LOCATION_FILE=" "

while getopts ":v:l:o:" opt; do
  case $opt in
    v) VEHICLE_FILE="""$OPTARG"""
    ;;
    l) LOCATION_FILE="""$OPTARG"""
    ;;
    o) OUTPUT_FILE="""$OPTARG"""
    ;;
    \?) help
    ;;
  esac
done

if [ "$VEHICLE_FILE" == " " ]; then
  echo ""
  echo "ERROR: Missing vehicle file... "
  help
  exit 1
fi

if [ "$LOCATION_FILE" == " " ]; then
  echo "Missing location file... "
  help
  exit 1
fi

run "$VEHICLE_FILE" "$LOCATION_FILE" "$OUTPUT_FILE"
